// Generated by CIRCT firtool-1.62.0
module NeuralNetwork(
  input         clock,
                reset,
  input  [15:0] s_axis_tdata,
  input  [1:0]  s_axis_tkeep,
  input         s_axis_tvalid,
                s_axis_tlast,
  output        s_axis_tready,
  output [15:0] m_axis_tdata,
  output [1:0]  m_axis_tkeep,
  output        m_axis_tvalid,
                m_axis_tlast,
  input         m_axis_tready
);

  reg  transferCount;
  wire mAxis_data_tlast = transferCount & m_axis_tready;
  always @(posedge clock) begin
    if (reset)
      transferCount <= 1'h0;
    else
      transferCount <= ~mAxis_data_tlast & (s_axis_tvalid & s_axis_tlast | transferCount);
  end // always @(posedge)
  assign s_axis_tready = 1'h1;
  assign m_axis_tdata = mAxis_data_tlast ? 16'hFF10 : 16'h0;
  assign m_axis_tkeep = 2'h3;
  assign m_axis_tvalid = mAxis_data_tlast;
  assign m_axis_tlast = mAxis_data_tlast;
endmodule

