// Generated by CIRCT firtool-1.62.0
module MatrixModel(
  input        clock,
               reset,
  input  [7:0] s_axis_tdata,
  input  [1:0] s_axis_tkeep,
  input        s_axis_tvalid,
               s_axis_tlast,
  output       s_axis_tready,
  output [7:0] m_axis_tdata,
  output [1:0] m_axis_tkeep,
  output       m_axis_tvalid,
               m_axis_tlast,
  input        m_axis_tready
);

  reg  outputReady;
  reg  outputCounter;
  wire mAxis_data_tvalid = outputReady & m_axis_tready;
  always @(posedge clock) begin
    if (reset) begin
      outputReady <= 1'h0;
      outputCounter <= 1'h0;
    end
    else begin
      outputReady <= s_axis_tlast | outputReady;
      if (mAxis_data_tvalid)
        outputCounter <= outputCounter - 1'h1;
    end
  end // always @(posedge)
  assign s_axis_tready = 1'h1;
  assign m_axis_tdata = 8'h0;
  assign m_axis_tkeep = 2'h1;
  assign m_axis_tvalid = mAxis_data_tvalid;
  assign m_axis_tlast = 1'h0;
endmodule

